[package]
name = "backoutmasterkey"
version = "0.1.0"
authors = ["Gregory Sanders <gsanders87@gmail.com>"]

[dependencies]
bitcoin = { version = "0.32.5", features = ["util", "base58"] }

secp256k1 = "0.30.0"
hex-literal = "0.1.0"
